import { defineConfig } from 'orval';

const outputTarget =
  process.env['TRINITY_ORVAL_OUTPUT_TARGET'] ??
  'src/app/api/generated/admin-api.ts';

export default defineConfig({
  adminApi: {
    input: {
      target: '../push-gateway/openapi/admin-v1.yaml',
    },
    output: {
      baseUrl: {
        getBaseUrlFromSpecification: true,
      },
      clean: true,
      client: 'angular',
      formatter: 'prettier',
      headers: false,
      mode: 'tags-split',
      override: {
        angular: {
          provideIn: 'root',
          retrievalClient: 'httpClient',
        },
        header: () => [
          'Generated by Orval from apps/push-gateway/openapi/admin-v1.yaml.',
          'Do not edit manually. Run pnpm nx run push-gateway-ui:generate-api.',
        ],
        requestOptions: false,
      },
      target: outputTarget,
    },
  },
});
