export const ADMIN_CONFIGURATION_ENVIRONMENT_NAMES = [
  'TRINITY_PUSH_GATEWAY_ADMIN_ENABLED',
  'TRINITY_PUSH_GATEWAY_ADMIN_PUBLIC_ORIGIN',
  'TRINITY_PUSH_GATEWAY_ADMIN_ASSETS_PATH',
  'TRINITY_PUSH_GATEWAY_ADMIN_DATABASE_PATH',
  'TRINITY_PUSH_GATEWAY_ADMIN_MIGRATIONS_PATH',
  'TRINITY_PUSH_GATEWAY_ADMIN_BACKUP_DIRECTORY',
  'TRINITY_PUSH_GATEWAY_ADMIN_BACKUP_LIMIT_COUNT',
  'TRINITY_PUSH_GATEWAY_ADMIN_BACKUP_LIMIT_BYTES',
  'TRINITY_PUSH_GATEWAY_ADMIN_OIDC_ISSUER',
  'TRINITY_PUSH_GATEWAY_ADMIN_OIDC_CLIENT_ID',
  'TRINITY_PUSH_GATEWAY_ADMIN_OIDC_CLIENT_SECRET',
  'TRINITY_PUSH_GATEWAY_ADMIN_OIDC_CLIENT_SECRET_FILE',
  'TRINITY_PUSH_GATEWAY_ADMIN_OIDC_SCOPES',
  'TRINITY_PUSH_GATEWAY_ADMIN_OIDC_GROUP_CLAIM',
  'TRINITY_PUSH_GATEWAY_ADMIN_OIDC_REQUIRED_GROUP',
  'TRINITY_PUSH_GATEWAY_ADMIN_OIDC_TOKEN_ENDPOINT_AUTH_METHOD',
  'TRINITY_PUSH_GATEWAY_ADMIN_SESSION_SECRET',
  'TRINITY_PUSH_GATEWAY_ADMIN_SESSION_SECRET_FILE',
] as const;

export type AdminConfigurationEnvironmentName =
  (typeof ADMIN_CONFIGURATION_ENVIRONMENT_NAMES)[number];
