export const SHARED_CONFIGURATION_DEFAULTS = Object.freeze({
  TRINITY_PUSH_GATEWAY_MAX_BODY_BYTES: '65536',
  TRINITY_PUSH_GATEWAY_MAX_DAILY_ATTEMPTS: '20000',
  TRINITY_PUSH_GATEWAY_MAX_DEVICES: '49',
  TRINITY_PUSH_GATEWAY_PENDING_LEASE_SECONDS: '120',
  TRINITY_PUSH_GATEWAY_REQUEST_DEADLINE_SECONDS: '30',
  TRINITY_PUSH_GATEWAY_TERMINAL_RETENTION_SECONDS: '86400',
  TRINITY_PUSH_GATEWAY_UPSTREAM_TIMEOUT_SECONDS: '10',
});

export const BUN_CONFIGURATION_DEFAULTS = Object.freeze({
  TRINITY_PUSH_GATEWAY_CLEANUP_INTERVAL_SECONDS: '86400',
  TRINITY_PUSH_GATEWAY_CLIENT_IP_HEADER: 'x-forwarded-for',
  TRINITY_PUSH_GATEWAY_DATABASE_PATH: '/data/gateway.sqlite',
  TRINITY_PUSH_GATEWAY_HOST: '0.0.0.0',
  TRINITY_PUSH_GATEWAY_MAX_SOURCE_KEYS: '10000',
  TRINITY_PUSH_GATEWAY_MIGRATIONS_PATH: '/app/migrations',
  TRINITY_PUSH_GATEWAY_PORT: '3000',
  TRINITY_PUSH_GATEWAY_SOURCE_RATE_LIMIT: '300',
  TRINITY_PUSH_GATEWAY_SOURCE_RATE_PERIOD_SECONDS: '10',
  TRINITY_PUSH_GATEWAY_TRUSTED_PROXY_CIDRS: '',
});
